### PR TITLE
Add schema:dump command

### PR DESCRIPTION
**Pull request by jorgemudry**
What does this Pull Request Do?
-------------------------------
It adds the `schema:dump` command (issue: https://github.com/flipboxstudio/lumen-generator/issues/94).

🔴 NOTE: You must have the component `illuminate/database` using the version >=v8.12.0 (because of [this change](https://github.com/illuminate/database/commit/23e82b209bf74a1c8211530d74a93bc292d87c4b))

How should this be manually tested?
-----------------------------------
1. Add the fork to your `composer.json` file:

```json
    "require": {
        "php": "^7.3|^8.0",
        "laravel/lumen-framework": "^8.0",
        "flipbox/lumen-generator": "dev-feature_add_schema_dump_command"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/jorgemudry/lumen-generator"
        }
    ]
```

2. Install the package:

```bash
$ composer update flipbox/lumen-generator;
```

3. Use the `schema:dump` command:

```bash
$ php artisan schema:dump
```

4. You should end up with a `your-connection-name-schema.dump` file in your `database/schema` directory.

Any background context you want to provide?
-------------------------------------------
N/A
 
Any extra info?
---------------
anne

### CODE REVIEW

**Comment by jorgemudry** [comment]
@aqidd are you worried about this PR's requirement?

**Comment by joelhy** [comment]
@aqidd 
I would like to propose that adding @jorgemudry as a collaborator.

**Comment by aqidd** [comment]
Hi guys sorry I was super busy with my thesis that I forgot about this one. There was a conflict before so I didn't merge it with the last release.

Good idea @joelhy - would you like to be a contributor @jorgemudry ?

**Comment by jorgemudry** [comment]
@aqidd @joelhy I have no idea what that means but yes, of course 😃

**Comment by joelhy** [comment]
That means you can merge pull request, manage comments, issues, and create new release etc.
Welcome aboard!  @jorgemudry 

Collaborator's permission list:
https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-for-a-repository-owned-by-a-user-account

**Comment by jorgemudry** [comment]
@joelhy thanks!!! 😃

**Pull request merged**
