### PR TITLE
Add a package suggestion into the composer.json

### PR DESCRIPTION
**Pull request by jorgemudry**
What does this Pull Request Do?
-------------------------------
It adds a new package suggestion into the `composer.json` file.

How should this be manually tested?
-----------------------------------
1. Install the package:

```bash
$ composer require flipbox/lumen-generator:dev-add_package_suggestion
```

2. You should see the suggested package (if you are using composer 2.0, you need to run `composer suggests` in order to see the suggestions).

Any background context you want to provide?
-------------------------------------------
This library has a `make:request` command that generates a form request class. That class depends on [this library](https://github.com/ssi-anik/form-request) (mainly because Lumen does not support form requests out of the box). That why the suggestion was added.

Any extra info?
---------------
axel

### CODE REVIEW

**Review by aqidd — APPROVED** [review]
lgtm 👍🏽

**Comment by joelhy** [comment]
LGTM

**Review by joelhy — APPROVED** [review]
LGTM 👍

**Comment by jorgemudry** [comment]
@aqidd @joelhy are you guys following the [Semantic Versioning](https://semver.org/) recommendations for the releases?

If that so, should we tag this as 8.2.0? (I'm asking so I don't break anything 😅)

**Comment by ssi-anik** [comment]
@jorgemudry I checked and found that it suggests my package. Thank you guys. <3

**Comment by aqidd** [comment]
Yeps. please tag with 8.2.0

Packagist then will auto-update it

Thanks man!

**Pull request merged**
